### ISSUE TITLE
REDIS TTL does not set for keyvalue and hashset data structure

### ISSUE THREAD

**Issue by kevinbheda** [odpf/firehose#152]
## 🐛 Bug Report
TTL is not set for hashset and keyvalue redis data type
## Expected Behavior
TTL should be set

## Steps to Reproduce
Steps to reproduce the behavior.
1.SET SINK_REDIS_TTL_TYPE: DURATION|EXACT_TIME
2.SET SINK_REDIS_TTL_VALUE: 1000 in seconds |<unix_timestamp_in_future>
3. Run the fireshose

**Comment by Meghajit** [comment]
Fixed as part of https://github.com/odpf/firehose/pull/154 and https://github.com/odpf/firehose/pull/153
@kevinbheda
