### ISSUE TITLE
[DOC] Kafka-Connect - comparaison unclear

### ISSUE THREAD

**Issue by raphaelauv** [odpf/firehose#176]
`
    Ease of use: Firehose is easier to install, and using different sinks only requires changing a few configurations. When used in distributed mode across multiple nodes, it requires connectors to be installed across all the workers within your Kafka-Connect cluster.`
    
 I don't understand that sentence , what is easier ?   
    
------------
`
Filtering: Value-based filtering is much easier to implement as compared to Kafka-Connect. Requires no additional plugins/schema-registry to be installed.`
    
 same there are pre existing filter , transformation in kafka connect -> https://kafka.apache.org/documentation/#connect_included_transformation
 
 and you can add other open source or create your own transformation , what is easier with firehose ?

------------
    
`
    Extensible: Provides a comprehensible abstract sink contract making it easier to add a new sink in Firehose. Firehose also comes with an inbuilt serialization/deserialization and doesn't require any converters and serializers when implementing a new sink.
`

again kafka-connect come by default with some serializers example org.apache.kafka.connect.json.JsonConverter
and if you need others you can add them , what is different with firehose ?

if I have confluent schema-registry then I will need avro deser/ser also in firehose
     
------------

`
Connectors: Some of the Kafka connect available connectors usually have limitations. Its usually rare to find all the required features in a single connector and so is to find documentation for the same
`

this is not relating to kafka-connect itself , your firehose connectors will also be opinionated 

------------
`
    Fully open-source: Firehose is completely open-source while separation of commercial and open-source features is not very structured in Kafka Connect and for monitoring and advanced features, confluent control center requires an enterprise subscription
`

kafka-connect is  fully open-source: , the fact that confluent is not open sourcing all the connectors they build is not related to kafka-connect itself
 
and for monitoring ( like debezium ) all specific connectors metrics are available in JMX

also they are multiple great open source UI for kafka-connect like https://github.com/provectus/kafka-ui

------

### A fair comparison would be great  where you simply and factually list the differences

like 

`firehose is a kafka-connect sink server alternative`

- not capable of doing source 
- not compatible with existing kafka-connect sink connectors
- is not using kafka topics to store configurations of the cluster but ...
- not using JMX to expose metrics but ...
- ...

**Comment by ravisuhag** [comment]
1. Unlike kafka connector firehose does not require you to manage connect plugins and only a configuration change is required to switch ot configure different sinks. Which makes it easy to use when you need for multiple sinks. 
2. Same as first one.

**Comment by raphaelauv** [comment]
Unlike kafka connector firehose does not require you to manage connect plugins


You mean firehose can dynamically download a new plugging without restarting the process?

In all case it's a bad practice, it's better to have all the source code in the static container image, that mean you can restart you container without any side effect of a plugging repository not answering

**Comment by ravisuhag** [comment]
I meant Firehose packs all available sinks. So users do not have to manage plugins on their own. All sinks are packed in a single jar and single container. 

I closed the issue because for now, we have removed the comparison from the documentation page. We will add the comparison again when we are finished with the benchmarks.

**Comment by ravisuhag** [comment]
You can create a custom connector in firehose but it does not require any other system to work. Consumer, Serde, filters, DLQ, sinks, and other features are bundled together and the same binary can be used to confirm any of the sinks you want. Firehose is built with ease of use in mind for sinks that are already there in it. And extensible when sinks are not available already.

**Comment by raphaelauv** [comment]
I'm lost, your not precise in your vocabulary

It's probably clear on your mind but it's very confuse for me.

I still don't understand what is offering this project

And I'm tired to try, bye

**Comment by ravisuhag** [comment]
No issue. Thanks for your effort and contribution :) Feel free to connect again.
