### ISSUE TITLE
Upgrade gradle version

### ISSUE THREAD

**Issue by ravisuhag** [odpf/firehose#20]
Upgrade Gradle version to 6.8.3 to support the latest OpenJDK version.

**Comment by rachittshah** [comment]
Can I work on this?

cc : @ravisuhag @lavkesh

**Comment by ravisuhag** [comment]
@rachittshah Assigning it to you. We want to release it as part of firehose 0.2 with BQ and GCS sink. So we aim to close it by next week. Let maintainers know if you need any help.

**Comment by rachittshah** [comment]
Thank you. I would update if I have any issues, would share the  progress

**Comment by vaish3496** [comment]
Hi @ravisuhag this issue seems to be inactive. I would like to work on this. I will be making a PR soon. I'll let you know if I face any kind of issues. Thanks!
